name: lint

on:
  push:
    branches: [ main ]
  pull_request:


env:
  UV_VERSION: "0.5.18"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.11"
    steps:
    - uses: actions/checkout@v3
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: ${{ env.UV_VERSION }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Install dependencies
      run: |
        uv pip install -e ".[dev]"
    - name: Analyzing the code with our lint
      run: |
        make lint
