name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --extra dev
    - name: Build
      run: uv build

  publish:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.10' ]
    steps:
    - uses: actions/checkout@v2
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: uv sync --extra dev
    - name: Build
      run: uv build
    - name: Publish to PyPI
      run: |
        uv publish --username "__token__" --password "$PYPI_API_TOKEN"
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
