name: Release

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Install dependencies
      run: uv pip install build
    - name: Build
      run: python -m build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Build and Publish to PyPI
      run: |
        uv pip install build twine
        python -m build
        python -m twine upload dist/* -u __token__ -p $PYPI_API_TOKEN
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
