name: Test

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - "3.10"
        - "3.13"
        # - "3.12"
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies (Essential Only)
      run: uv sync
    - name: Confirm Library Imports
      run: uv run python -c "import semantic_router"
    - name: Install Dependencies (All)
      run: uv sync --extra dev
    - name: Pytest All
      env:
        PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        make test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
